# Feature engineering

In [4]:
import pandas as pd
import numpy as np

In [8]:
agg = pd.read_csv('data/aggregates.csv')
trans = pd.read_csv('data/transactions.csv')

cnt_zp_1m  cnt_zp_3m  cnt_zp_6m  cnt_zp_12m  \
client_id report_date                                                        
0         2019-09-01 00:00:00        1.0        1.0        1.0         1.0   
          2019-10-01 00:00:00        1.0        2.0        2.0         2.0   
          2019-11-01 00:00:00        1.0        3.0        3.0         3.0   
          2019-12-01 00:00:00        1.0        3.0        4.0         4.0   
          2020-01-01 00:00:00        2.0        4.0        6.0         6.0   

                               downlimit_count  uplimit_count  \
client_id report_date                                           
0         2019-09-01 00:00:00              0.0            0.0   
          2019-10-01 00:00:00              0.0            0.0   
          2019-11-01 00:00:00              0.0            0.0   
          2019-12-01 00:00:00              0.0            0.0   
          2020-01-01 00:00:00              0.0            0.0   

                               limit_exchange_count  cur_credit_limit  \
client_id report_date                                                   
0         2019-09-01 00:00:00                   0.0               0.0   
          2019-10-01 00:00:00                   0.0               0.0   
          2019-11-01 00:00:00                   0.0               0.0   
          2019-12-01 00:00:00                   0.0               0.0   
          2020-01-01 00:00:00                   0.0               0.0   

                               cur_cr_lim_month  prev_credit_limit  ...  \
client_id report_date                                               ...   
0         2019-09-01 00:00:00               0.0                0.0  ...   
          2019-10-01 00:00:00               0.0                0.0  ...   
          2019-11-01 00:00:00               0.0                0.0  ...   
          2019-12-01 00:00:00               0.0                0.0  ...   
          2020-01-01 00:00:00               0.0                0.0  ...   

                               curdel_30plus_bki  curdel_60plus_bank  \
client_id report_date                                                  
0         2019-09-01 00:00:00                0.0                 0.0   
          2019-10-01 00:00:00                0.0                 0.0   
          2019-11-01 00:00:00                0.0                 0.0   
          2019-12-01 00:00:00                0.0                 0.0   
          2020-01-01 00:00:00                0.0                 0.0   

                               curdel_60plus_bki  curdel_tech_bank  \
client_id report_date                                                
0         2019-09-01 00:00:00                0.0               0.0   
          2019-10-01 00:00:00                0.0               0.0   
          2019-11-01 00:00:00                0.0               0.0   
          2019-12-01 00:00:00                0.0               0.0   
          2020-01-01 00:00:00                0.0               0.0   

                               curdel_tech_bki  bank_1_29_5y_debtor  \
client_id report_date                                                 
0         2019-09-01 00:00:00              0.0                  0.0   
          2019-10-01 00:00:00              0.0                  0.0   
          2019-11-01 00:00:00              0.0                  0.0   
          2019-12-01 00:00:00              0.0                  0.0   
          2020-01-01 00:00:00              0.0                  0.0   

                               bank_30_59_5y_debtor  bank_60_89_5y_debtor  \
client_id report_date                                                       
0         2019-09-01 00:00:00                   0.0                   0.0   
          2019-10-01 00:00:00                   0.0                   0.0   
          2019-11-01 00:00:00                   0.0                   0.0   
          2019-12-01 00:00:00                   0.0                   0.0   
          2020-01-01 00:00:00     

In [9]:
agg.fillna(0, inplace = True)
agg.head()

group_predict
0              0
1              1
2              0
3              0
4              1

In [10]:
trans.head()

In [11]:
agg = agg.groupby(['client_id', 'report_date']).sum()

/home/danila/anaconda3/lib/python3.7/site-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [16]:
agg.head()

array([[6.66156792e-174, 3.40713676e-196, 1.50252702e-172,
        1.98735344e-140, 5.46792858e-235, 1.04911383e-164,
        2.37027747e-264, 1.12693974e-170, 0.00000000e+000,
        3.77817247e-105, 1.97022001e-108, 1.71507478e-120,
        1.26212855e-067, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 1.00000000e+000,
        0.00000000e+000, 1.68012325e-209, 0.00000000e+000,
        1.23628463e-018, 0.00000000e+000]])

In [ ]:
trans['mcc_group'].value_counts().index

In [17]:
df = trans
col = trans['mcc_group'].value_counts().index
for name in col:
    df[name] = 0
    df[name] = df.loc[df.mcc_group == name]['att_sum']

/home/danila/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [18]:
df.fillna(0, inplace = True)
df.head()

0.74875

In [40]:
df = df.groupby(['client_id', 'last_day_month']).sum().iloc[:,5:]

array([7.41025232e-01, 1.28338693e-01, 4.71884760e-02, 3.08096825e-02,
       1.39402982e-02, 1.03181866e-02, 1.25680568e-02, 4.80983228e-03,
       2.61264578e-03, 1.09399894e-03, 6.97535685e-04, 1.75443269e-03,
       5.54081026e-04, 7.86016503e-04, 3.09940626e-04, 6.46167206e-04,
       2.52065889e-04, 4.65525023e-04, 4.88726295e-04, 7.29801115e-04,
       2.54228476e-04, 2.44395213e-04, 1.11982214e-04])

In [45]:
df.head()

0    2400
Name: 0, dtype: int64

In [27]:
df['max_group'] = [df.columns[i][0] for i in df.values == df.max(axis=1)[:,None]]

0     9001
1     1459
2      541
3      392
4      163
6      132
5      125
7       60
8       25
11      25
9       15
10      11
13       9
12       8
19       7
15       6
18       5
17       5
14       3
20       2
21       2
16       2
24       1
22       1
Name: group_predict, dtype: int64

In [ ]:
df.head()

In [46]:
df.reset_index('last_day_month', inplace = True)
df.head()

/home/danila/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [47]:
df['year_month'] = 0
for date in df['last_day_month'].value_counts().index:
    df.loc[df.last_day_month == date, 'year_month'] = str(pd.to_datetime(date).year) + '_' + str(pd.to_datetime(date).month)
    print(date)


0.74

In [50]:
agg.reset_index('report_date', inplace = True)
agg['year_month'] = 0
for date in agg['report_date'].value_counts().index:
    agg.loc[agg.report_date == date, 'year_month'] = str(pd.to_datetime(date).year) + '_' + str(pd.to_datetime(date).month)
    print(date)

0     1918
1      241
3       75
2       74
4       31
6       22
5       15
7        5
11       4
17       2
12       2
8        2
21       2
13       2
10       1
16       1
19       1
9        1
22       1
Name: 0, dtype: int64

In [56]:
agg.reset_index(inplace = True)
df.reset_index(inplace = True)
agg.head()

array([0.99, 0.01, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  ])

In [ ]:
merged = pd.merge(agg, df[['client_id','year_month', 'max_group']], on=['client_id', 'year_month'])

In [20]:
merged.drop('year_month', axis = 1, inplace = True)
merged.head()

/home/danila/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/danila/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_stochastic_gradient.py:557: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [21]:
merged['group_predict'] = 0
groups = merged['max_group'].value_counts().index
for i in range(len(groups)):
    merged.loc[merged.max_group == groups[i], 'group_predict'] = i

0.55

In [ ]:
merged.drop('max_group',axis=1,inplace = True)

In [ ]:
merged.head()

In [ ]:
merged = merged[:30000]

# Machine Learning

In [ ]:
X = merged.iloc[:,:-1]
y = merged.iloc[:,-1:]
X.to_csv('data/X.csv')
y.to_csv('data/y.csv')

In [ ]:
del merged, trans

In [ ]:
X = X.groupby(['client_id', 'report_date']).sum()
X.head()

In [ ]:
y.head()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)